---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :enabled # :audit_only, :enabled, :disabled

platforms:
  - name: ubuntu-14.04
  # - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[ssh::default]
    attributes:
